"""init

Revision ID: 77558d3932c7
Revises: 
Create Date: 2024-12-24 16:21:23.751310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Ajouté


# revision identifiers, used by Alembic.
revision: str = '77558d3932c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
