"""Add ChatLog table

Revision ID: 9ddd0b716208
Revises: 
Create Date: 2025-01-10 15:59:48.615700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Ajouté
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ddd0b716208'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatlog')
    op.alter_column('chat_logs', 'question',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_logs', 'response',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chat_logs', 'response',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('chat_logs', 'question',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.create_table('chatlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chatlog_pkey')
    )
    # ### end Alembic commands ###
