services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_USER: test
      POSTGRES_DB: fastapi
      POSTGRES_PASSWORD: test

    ports:
      - "5432:5432"

    volumes:
      - postgres-db-data:/var/lib/postgresql/data

    networks:
      - app-network


  vector_db:
    image: qdrant/qdrant:latest

    ports:
      - "6333:6333"

    volumes:
      - qdrant-db-data:/var/lib/qdrant/data

    networks:
      - app-network

    healthcheck:
      test: ["CMD", "echo", "GET /health HTTP/1.1\n\n" , ">/dev/tcp/localhost/6333"]
      interval: 30s
      timeout: 10s
      retries: 5

  # file:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile-test
  #   volumes:
  #     - ./:/app
  #   env_file:
  #     - .env.example



volumes:
  postgres-db-data:
  qdrant-db-data:

networks:
  app-network:
    driver: bridge
    